### ISSUE TITLE
Error when searching for a definition

### ISSUE THREAD

**Issue by Incognitux** [xueyuanl/cambrinary#17]
Running `cambrinary -w <word>` returns:
```Traceback (most recent call last):
  File "/home/incognitux/.local/bin/cambrinary", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/incognitux/.local/lib/python3.11/site-packages/cambrinary/cambrinary.py", line 135, in main
    loop.run_until_complete(asyncio.wait(tasks))
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'look_up' was never awaited
```
on Fedora Linux 37

**Comment by Incognitux** [comment]
So I tested it on Linux Mint and it seems to be working as expected, the problem seems to be with Fedora here.
Maybe because Fedora is more bleeding edge has to do something with it?

**Comment by LuGHuaaa** [comment]
mac m1 has the same question.
