### ISSUE TITLE
Fails to suggest definitions everytime

### ISSUE THREAD

**Issue by ArcherN9** [xueyuanl/cambrinary#7]
Hi, thanks for maintaining this project. I use it almost everyday!

The application was working fine until yesterday. I keep receiving a response: NONE whenever I attempt to retrieve a definition.

```
~
$ cambrinary --word gratitude
None

~
$
```

Contents of a fresh `dict.log`.

```
2020-07-24 09:25:45,383 - /usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py[line:59] - DEBUG: Using selector: KqueueSelector
2020-07-24 09:25:45,383 - /Users/xxx/Library/Python/3.8/lib/python/site-packages/cambrinary/cambrinary.py[line:322] - INFO: start to work...
2020-07-24 09:25:45,384 - /Users/xxx/Library/Python/3.8/lib/python/site-packages/cambrinary/cambrinary.py[line:293] - INFO: begin to retrieve word: [gratitude] in english
2020-07-24 09:25:46,415 - /usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py[line:1707] - ERROR: Task exception was never retrieved
future: <Task finished name='Task-2' coro=<look_up() done, defined at /Users/xxx/Library/Python/3.8/lib/python/site-packages/cambrinary/cambrinary.py:292> exception=ServerDisconnectedError()>
Traceback (most recent call last):
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/cambrinary/cambrinary.py", line 294, in look_up
    html = await load(word, translation[trans])
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/cambrinary/cambrinary.py", line 37, in load
    async with aiohttp.request('GET', url) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1051, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

When I visit `https://dictionary.cambridge.org/` on a browser, I receive a `Secure Connection Failed` error. I checked DNS resolution and it seems to be resolving fine. Doesn't seem to be Cambrinary's issue.. but why can't I access Cambridge dictionary though?

**Comment by xueyuanl** [comment]
Hi, 

Thanks for your usage. It's a great motivation for me to keep going. And I also hit this error today.
I will dive into it these days, maybe two or three days needed.

Thanks

**Comment by xiangpeng2008** [comment]
Same issue.

**Comment by xueyuanl** [comment]
Hi @ArcherN9 and @xiangpeng2008 ,

It should be ok now. Use `pip3 install --upgrade cambrinary` to update.

More details:

I simply change to another scheme, which is using `curl` (curl -k -X GET <url>) to retrive the page instead of the aiothttp package.

Using aiohttp package can hit this error `certificate verify failed`. Maybe something changed from cambridge side.
And I try to ignore ssl verify, but did not work, refering: https://github.com/aio-libs/aiohttp/issues/955

**Comment by ArcherN9** [comment]
Works great for now! Thanks!
