### ISSUE TITLE
Fails on `cambrinary -w 'black'`

### ISSUE THREAD

**Issue by CookiePPP** [xueyuanl/cambrinary#8]
Found a word that fails to run on my system while playing around with your utility.
`cambrinary -w 'black'` and `cambrinary -w black` fail to run.

```
2021-02-17 06:49:44,086 - /home/cookie/anaconda3/lib/python3.7/asyncio/selector_events.py[line:53] - DEBUG: Using selector: EpollSelector
2021-02-17 06:49:44,087 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py[line:130] - INFO: start to work...
2021-02-17 06:49:44,087 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py[line:97] - INFO: begin to retrieve word: [black] in english
2021-02-17 06:49:44,494 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py[line:35] - INFO: successfully execute: curl -k -X GET https://dictionary.cambridge.org/dictionary/english/black
2021-02-17 06:49:44,685 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py[line:89] - INFO: get a dictionary by pr dictionary
2021-02-17 06:49:44,693 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py[line:106] - INFO: the number of part_speeh is 3
2021-02-17 06:49:44,693 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:273] - INFO: parse the 0th part_speech
2021-02-17 06:49:44,693 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:99] - INFO: the pronunciation is: adjective [0;34;49mUK[0m [0;39;49m/blæk/[0m [0;34;49mUS[0m [0;39;49m/blæk/[0m 

2021-02-17 06:49:44,701 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:247] - INFO: the number of block is 4
2021-02-17 06:49:44,701 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:249] - INFO: parse the 0th block
2021-02-17 06:49:44,701 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:168] - INFO: fetch the dsense_h
2021-02-17 06:49:44,702 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:181] - INFO: the  title of block is [0;39;49m[COLOUR][0m adjective

2021-02-17 06:49:44,702 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:186] - INFO: the number of pad_indent is 1
2021-02-17 06:49:44,703 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:249] - INFO: parse the 1th block
2021-02-17 06:49:44,703 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:168] - INFO: fetch the dsense_h
2021-02-17 06:49:44,704 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:181] - INFO: the  title of block is [0;39;49m[PEOPLE][0m adjective

2021-02-17 06:49:44,705 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:186] - INFO: the number of pad_indent is 1
2021-02-17 06:49:44,705 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:249] - INFO: parse the 2th block
2021-02-17 06:49:44,705 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:168] - INFO: fetch the dsense_h
2021-02-17 06:49:44,706 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:181] - INFO: the  title of block is [0;39;49m[COFFEE/TEA][0m adjective

2021-02-17 06:49:44,707 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:186] - INFO: the number of pad_indent is 1
2021-02-17 06:49:44,707 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:249] - INFO: parse the 3th block
2021-02-17 06:49:44,707 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:168] - INFO: fetch the dsense_h
2021-02-17 06:49:44,708 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:181] - INFO: the  title of block is [0;39;49m[BAD][0m adjective

2021-02-17 06:49:44,708 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:186] - INFO: the number of pad_indent is 2
2021-02-17 06:49:44,709 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:273] - INFO: parse the 1th part_speech
2021-02-17 06:49:44,710 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:99] - INFO: the pronunciation is: noun [0;34;49mUK[0m [0;39;49m/blæk/[0m [0;34;49mUS[0m [0;39;49m/blæk/[0m 

2021-02-17 06:49:44,713 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:247] - INFO: the number of block is 2
2021-02-17 06:49:44,713 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:249] - INFO: parse the 0th block
2021-02-17 06:49:44,713 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:168] - INFO: fetch the dsense_h
2021-02-17 06:49:44,715 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:181] - INFO: the  title of block is [0;39;49m[COLOUR][0m noun

2021-02-17 06:49:44,715 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:186] - INFO: the number of pad_indent is 2
2021-02-17 06:49:44,716 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:249] - INFO: parse the 1th block
2021-02-17 06:49:44,716 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:168] - INFO: fetch the dsense_h
2021-02-17 06:49:44,717 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:181] - INFO: the  title of block is [0;39;49m[PEOPLE][0m noun

2021-02-17 06:49:44,717 - /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py[line:186] - INFO: the number of pad_indent is 1
2021-02-17 06:49:44,718 - /home/cookie/anaconda3/lib/python3.7/asyncio/base_events.py[line:1604] - ERROR: Task exception was never retrieved
future: <Task finished coro=<look_up() done, defined at /home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py:96> exception=AttributeError("'NoneType' object has no attribute 'find'")>
Traceback (most recent call last):
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/cambrinary.py", line 110, in look_up
    word_obj.parse_part_speeches(part_speeches)
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py", line 276, in parse_part_speeches
    part_speech.parse_sense_blocks(p)
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py", line 252, in parse_sense_blocks
    sense_block.parse_pad_indents(block)
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py", line 195, in parse_pad_indents
    pad_indent.parse_trans(def_body)
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/cambrinary/type.py", line 124, in parse_trans
    trans = body.find('span', attrs={'class': 'trans dtrans dtrans-se'}, recursive=False)
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by CookiePPP** [comment]
checking [the site](https://dictionary.cambridge.org/dictionary/english/black)
The final `def-block ddef_block` div is missing the `def-body ddef_b` so [`def_body`](https://github.com/xueyuanl/cambrinary/blob/25dd76fba53a7f5d403c482ec0c4a0abb5f7e9d9/cambrinary/type.py#L189-L191) is left as None.

```HTML
<div class="def-block ddef_block " data-wl-senseid="CBED_00001451_06">
                        <div class="dwl hax">
        <a amp-access="loggedIn" amp-access-hide="" class="dwla wordlist-add-button" title="Add this meaning to a word list" on="tap:AMP.setState({ stateGlobal: { wlSenseId: 'CBED_00001451_06' } }), sidebarWordList.open">
            <i class="i i-plus" aria-hidden="true"></i>
            <i class="i i-list-ul"></i>
        </a>
        <a amp-access="NOT loggedIn" class="dwla wordlist-add-button" title="Add this meaning to a word list" on="tap:amp-access.login-sign-in">
            <i class="i i-plus" aria-hidden="true"></i>
            <i class="i i-list-ul"></i>
        </a>
    </div>
                <div class="ddef_h"><span class="def-info ddef-info">  <span class="lab dlab"><span class="region dregion">UK</span></span></span> <div class="def ddef_d db">if a <a class="query" href="https://dictionary.cambridge.org/dictionary/english/trade" title="trade">trade</a> <a class="query" href="https://dictionary.cambridge.org/dictionary/english/union" title="union">union</a> blacks <a class="query" href="https://dictionary.cambridge.org/dictionary/english/goods" title="goods">goods</a>, an <a class="query" href="https://dictionary.cambridge.org/dictionary/english/organization" title="organization">organization</a>, etc. it <a class="query" href="https://dictionary.cambridge.org/dictionary/english/refuse" title="refuses">refuses</a> to <a class="query" href="https://dictionary.cambridge.org/dictionary/english/deal" title="deal">deal</a> with them </div> </div></div>
```

---

I'll check if the HTML tree for this block is similar to the normal blocks, hopefully you can just add it to `pad.find` or ignore it.

**Comment by CookiePPP** [comment]
Alright, was able to get it working by adding some `if body is not None` statements to the `parse_trans`, `parse_example`, `parse_synonym` funcs.

PR is [here](https://github.com/xueyuanl/cambrinary/pull/9)

**Comment by xueyuanl** [comment]
Really appreciate for your great contribution. I ignored the None case when I did some refine works, and yes it's a serious problem in some situations.
